const div = dom.create('<div>newDiv</div>')
console.log(div)
dom.after(test, div)
const div2 = dom.create('<div id =\'parent\'></div>')
dom.wrap(test, div2)
console.log(dom.empty(empty))
dom.attr(test, 'title', 'hi')
console.log(dom.attr(test, 'title'))
dom.text(test, '这是一条新的内容')
dom.html(test, '<p>这是一条p标签</p>')
dom.style(test, {color: 'red',border: '1px solid red'})
console.log(dom.style(test, 'color'))
dom.style(test, 'color', 'blue')
dom.class.add(test,'red')
dom.class.remove(test,'red')
console.log(dom.class.has(test,'red'))
fn=()=>{
    console.log('click once')
}
dom.on(test,'click',fn)
dom.off(test,'click',fn)
//因为dom.find返回的是一个数组，所以若想返回内容须取其第0项
console.log(dom.find('#test')[0])
console.log(dom.find('.red',test2)[0])
console.log(dom.parent(test))
console.log(dom.siblings(dom.find('#s2')[0]))
console.log(dom.next(dom.find('#s2')[0]))
console.log(dom.previous(dom.find('#s2')[0]))
dom.travel(dom.children(dom.find('#travel')[0]),(n)=>dom.style(n,'color','red'))
console.log(dom.index(s3))